// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// stata
List stata(const char * filePath, const bool missing);
RcppExport SEXP readstata13_stata(SEXP filePathSEXP, SEXP missingSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const char * >::type filePath(filePathSEXP );
        Rcpp::traits::input_parameter< const bool >::type missing(missingSEXP );
        List __result = stata(filePath, missing);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// stataWrite
int stataWrite(const char * filePath, Rcpp::DataFrame dat);
RcppExport SEXP readstata13_stataWrite(SEXP filePathSEXP, SEXP datSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const char * >::type filePath(filePathSEXP );
        Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dat(datSEXP );
        int __result = stataWrite(filePath, dat);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
