# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stata <- function(filePath, missing) {
    .Call('readstata13_stata', PACKAGE = 'readstata13', filePath, missing)
}

#' Writes the binary Stata file
#'
#' @param filePath The full systempath to the dta file you want to export.
#' @param dat an R-Object of class data.frame.
#' @export
stataWriteOld <- function(filePath, dat) {
    .Call('readstata13_stataWriteOld', PACKAGE = 'readstata13', filePath, dat)
}

stataWrite <- function(filePath, dat) {
    .Call('readstata13_stataWrite', PACKAGE = 'readstata13', filePath, dat)
}

