# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Writes the binary Stata file
#'
#' @param filePath The full systempath to the dta file you want to export.
#' @param dat an R-Object of class data.frame.
#' @export
stata_pre13_save <- function(filePath, dat) {
    .Call('readstata13_stata_pre13_save', PACKAGE = 'readstata13', filePath, dat)
}

stata_read <- function(filePath, missing) {
    .Call('readstata13_stata_read', PACKAGE = 'readstata13', filePath, missing)
}

stata_save <- function(filePath, dat) {
    .Call('readstata13_stata_save', PACKAGE = 'readstata13', filePath, dat)
}

