# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stata_pre13_save <- function(filePath, dat) {
    .Call('readstata13_stata_pre13_save', PACKAGE = 'readstata13', filePath, dat)
}

stata_read <- function(filePath, missing, selectrows) {
    .Call('readstata13_stata_read', PACKAGE = 'readstata13', filePath, missing, selectrows)
}

stata_save <- function(filePath, dat) {
    .Call('readstata13_stata_save', PACKAGE = 'readstata13', filePath, dat)
}

